[project]
name = "tracker-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rfdetr>=1.4.2",
    "supervision>=0.27.0.post1",
    "trackers>=2.1.0",
]
